apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backendapp
  labels: 
    app: backendapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata: 
      labels: 
        app: backendapp
        tier: backend
    spec:
      containers:
        - name: backendapp
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080

---

apiVersion: v1 
kind: Service 
metadata:
  name: mybackendapp
spec:
 selector: 
   app: backendapp
 ports:
   - port: 8080
     name: http
     targetPort: 8080