apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo2ss-deployment
  labels:
    app: acrdemo2s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo2s
  template:
    metadata:
      labels:
        app: acrdemo2s
    spec:
      containers:
        - name: acrdemo2ss-vn
          image: acrdemo2s.azurecr.io/app3/acr-app3:v1 # Update Image Name 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: acrdemo2s-secret  
# To schedule pods on Azure Virtual Nodes            
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule            


   