apiVersion: v1
kind: Service
metadata:
  name: acrdemo2s-loadbalancer-service
  labels:
    app: acrdemo2s
spec:
  type: LoadBalancer
  selector:
    app: acrdemo2s
  ports:
    - port: 80
      targetPort: 80
